/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFramework;

import ConfigureABusiness.BusinessData;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author aayus
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    //Courses courses;
            //CourseDirectory courseDirectory;
            TeachingHistory teachingHistory;
      TeachingHistoryDirectory teachingHistoryDirectory;
      private String loggedInProfessorId; 
    public MainJFrame() {
        
        initComponents();
        BusinessData.getInstance().test2();
       // courses = new Courses();
       // courseDirectory = new CourseDirectory();
        teachingHistory = new TeachingHistory();
        teachingHistoryDirectory = new TeachingHistoryDirectory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniversityPerformancePanel = new javax.swing.JPanel();
        UniversityPerformaceLabel = new javax.swing.JLabel();
        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        StudentLoginButton = new javax.swing.JButton();
        AdminLoginButton = new javax.swing.JButton();
        EmployerLoginButton = new javax.swing.JButton();
        FacultyLoginButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        UniversityPerformancePanel.setBackground(new java.awt.Color(23, 35, 51));

        UniversityPerformaceLabel.setBackground(new java.awt.Color(0, 0, 0));
        UniversityPerformaceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UniversityPerformaceLabel.setForeground(new java.awt.Color(255, 255, 255));
        UniversityPerformaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UniversityPerformaceLabel.setText("DIGITAL UNIVERSITY MODEL");
        UniversityPerformaceLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout UniversityPerformancePanelLayout = new javax.swing.GroupLayout(UniversityPerformancePanel);
        UniversityPerformancePanel.setLayout(UniversityPerformancePanelLayout);
        UniversityPerformancePanelLayout.setHorizontalGroup(
            UniversityPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UniversityPerformaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UniversityPerformancePanelLayout.setVerticalGroup(
            UniversityPerformancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UniversityPerformaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanel.setBackground(new java.awt.Color(0, 102, 102));
        controlPanel.setForeground(new java.awt.Color(57, 74, 78));

        StudentLoginButton.setBackground(new java.awt.Color(0, 204, 204));
        StudentLoginButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StudentLoginButton.setText("STUDENT");
        StudentLoginButton.setPreferredSize(new java.awt.Dimension(75, 25));
        StudentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLoginButtonActionPerformed(evt);
            }
        });

        AdminLoginButton.setBackground(new java.awt.Color(0, 204, 204));
        AdminLoginButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AdminLoginButton.setText("ADMIN");
        AdminLoginButton.setPreferredSize(new java.awt.Dimension(75, 25));
        AdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginButtonActionPerformed(evt);
            }
        });

        EmployerLoginButton.setBackground(new java.awt.Color(0, 204, 204));
        EmployerLoginButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EmployerLoginButton.setText("EMPLOYER");
        EmployerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployerLoginButtonActionPerformed(evt);
            }
        });

        FacultyLoginButton1.setBackground(new java.awt.Color(0, 204, 204));
        FacultyLoginButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FacultyLoginButton1.setText("FACULTY");
        FacultyLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyLoginButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AdminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(StudentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(FacultyLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(EmployerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(AdminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UniversityPerformancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(UniversityPerformancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginButtonActionPerformed
        // TODO add your handling code here:
        AdminjPanel adminLogin = new AdminjPanel();
        splitPane.setRightComponent(adminLogin);
    }//GEN-LAST:event_AdminLoginButtonActionPerformed

    private void EmployerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployerLoginButtonActionPerformed
        // TODO add your handling code here:
        EmployerjPanel employerLogin = new EmployerjPanel();
        splitPane.setRightComponent(employerLogin);
    }//GEN-LAST:event_EmployerLoginButtonActionPerformed

    private void StudentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLoginButtonActionPerformed
        // TODO add your handling code here:
       // StudentLoginPanel studentLogin = new StudentLoginPanel();
        StudentjPanel stdPanel = new StudentjPanel();
        splitPane.setRightComponent(stdPanel);
    }//GEN-LAST:event_StudentLoginButtonActionPerformed

    private void FacultyLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyLoginButton1ActionPerformed
        // TODO add your handling code here:
        ProfessorjPanel facultyPanel = new ProfessorjPanel(teachingHistory, teachingHistoryDirectory, loggedInProfessorId);
        splitPane.setRightComponent(facultyPanel);
    }//GEN-LAST:event_FacultyLoginButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginButton;
    private javax.swing.JButton EmployerLoginButton;
    private javax.swing.JButton FacultyLoginButton1;
    private javax.swing.JButton StudentLoginButton;
    private javax.swing.JLabel UniversityPerformaceLabel;
    private javax.swing.JPanel UniversityPerformancePanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
